# Understanding your data

The data is pre-loaded into a pandas DataFrame called df. Use the .head() and .describe() methods in the IPython Shell for a quick overview of the DataFrame.

The target variable you'll be predicting is wage_per_hour. Some of the predictor variables are binary indicators, where a value of 1 represents True, and 0 represents False.

Of the 9 predictor variables in the DataFrame, how many are binary indicators? The min and max values as shown by .describe() will be informative here. How many binary indicator predictors are there?

In [2]:
import pandas as pd
df = pd.read_csv("dataset/hourly_wages.csv")
df.head()

,wage_per_hour,union,education_yrs,experience_yrs,age,female,marr,south,manufacturing,construction
0,5.10,0,8,21,35,1,1,0,1,0
1,4.95,0,9,42,57,1,1,0,1,0
2,6.67,0,12,1,19,0,0,0,1,0
3,4.00,0,12,4,22,0,0,0,0,0
4,7.50,0,12,17,35,0,1,0,0,0

In [3]:
df.describe()

,wage_per_hour,union,education_yrs,experience_yrs,age,female,marr,south,manufacturing,construction
count,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000
mean,9.024064,0.179775,13.018727,17.822097,36.833333,0.458801,0.655431,0.292135,0.185393,0.044944
std,5.139097,0.384360,2.615373,12.379710,11.726573,0.498767,0.475673,0.455170,0.388981,0.207375
min,1.000000,0.000000,2.000000,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.250000,0.000000,12.000000,8.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.780000,0.000000,12.000000,15.000000,35.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,11.250000,0.000000,15.000000,26.000000,44.000000,1.000000,1.000000,1.000000,0.000000,0.000000
max,44.500000,1.000000,18.000000,55.000000,64.000000,1.000000,1.000000,1.000000,1.000000,1.000000

- There are 6 binary indicators.

# Specifying a model

Now you'll get to work with your first model in Keras, and will immediately be able to run more complex neural network models on larger datasets compared to the first two chapters.

To start, you'll take the skeleton of a neural network and add a hidden layer and an output layer. You'll then fit that model and see Keras do the optimization so your model continually gets better.

As a start, you'll predict workers wages based on characteristics like their industry, education and level of experience. You can find the dataset in a pandas DataFrame called df. For convenience, everything in df except for the target has been converted to a NumPy array called predictors. The target, wage_per_hour, is available as a NumPy array called target.

For all exercises in this chapter, we've imported the Sequential model constructor, the Dense layer constructor, and pandas.

In [4]:
predictors = df.drop("wage_per_hour", axis=1)
# Import necessary modules
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

# Save the number of columns in predictors: n_cols
n_cols = predictors.shape[1]

# Set up the model: model
model = Sequential()

# Add the first layer
model.add(Dense(50, activation='relu', input_shape=(n_cols,)))

# Add the second layer
model.add(Dense(32, activation='relu'))

# Add the output layer
model.add(Dense(1))

# Compiling the model

You're now going to compile the model you specified earlier. To compile the model, you need to specify the optimizer and loss function to use. In the video, Dan mentioned that the Adam optimizer is an excellent choice. You can read more about it as well as other Keras optimizers here, and if you are really curious to learn more, you can read the original paper that introduced the Adam optimizer.

In this exercise, you'll use the Adam optimizer and the mean squared error loss function. Go for it!

In [5]:
# Import necessary modules
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

# Specify the model
n_cols = predictors.shape[1]
model = Sequential()
model.add(Dense(50, activation='relu', input_shape = (n_cols,)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

# Verify that model contains information from compiling
print("Loss function: " + model.loss)

Loss function: mean_squared_error

# Fitting the model

 You'll now fit the model. Recall that the data to be used as predictive features is loaded in a NumPy array called predictors and the data to be predicted is stored in a NumPy array called target. Your model is pre-written and it has been compiled with the code from the previous exercise.

In [7]:
# Import necessary modules
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

# Specify the model
n_cols = predictors.shape[1]
model = Sequential()
model.add(Dense(50, activation='relu', input_shape = (n_cols,)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Fit the model
model.fit(predictors, df["wage_per_hour"])

17/17 [==============================] - 0s 1ms/step - loss: 27.3336

# Understanding your classification data

Now you will start modeling with a new dataset for a classification problem. This data includes information about passengers on the Titanic. You will use predictors such as age, fare and where each passenger embarked from to predict who will survive. This data is from a tutorial on data science competitions. Look here for descriptions of the features.

The data is pre-loaded in a pandas DataFrame called df.

It's smart to review the maximum and minimum values of each variable to ensure the data isn't misformatted or corrupted. What was the maximum age of passengers on the Titanic?

In [8]:
df = pd.read_csv("dataset/titanic_all_numeric.csv")
df.head()

,survived,pclass,age,sibsp,parch,fare,male,age_was_missing,embarked_from_cherbourg,embarked_from_queenstown,embarked_from_southampton
0,0,3,22.0,1,0,7.2500,1,False,0,0,1
1,1,1,38.0,1,0,71.2833,0,False,1,0,0
2,1,3,26.0,0,0,7.9250,0,False,0,0,1
3,1,1,35.0,1,0,53.1000,0,False,0,0,1
4,0,3,35.0,0,0,8.0500,1,False,0,0,1

In [9]:
df.describe()

,survived,pclass,age,sibsp,parch,fare,male,embarked_from_cherbourg,embarked_from_queenstown,embarked_from_southampton
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,0.647587,0.188552,0.086420,0.722783
std,0.486592,0.836071,13.002015,1.102743,0.806057,49.693429,0.477990,0.391372,0.281141,0.447876
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400,0.000000,0.000000,0.000000,0.000000
50%,0.000000,3.000000,29.699118,0.000000,0.000000,14.454200,1.000000,0.000000,0.000000,1.000000
75%,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000,1.000000,0.000000,0.000000,1.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000,1.000000,1.000000,1.000000

# Last steps in classification models

You'll now create a classification model using the titanic dataset, which has been pre-loaded into a DataFrame called df. You'll take information about the passengers and predict which ones survived.

The predictive variables are stored in a NumPy array predictors. The target to predict is in df.survived, though you'll have to manipulate it for Keras. The number of predictive features is stored in n_cols.

Here, you'll use the 'sgd' optimizer, which stands for Stochastic Gradient Descent.

In [15]:
import numpy as np
predictors = df.drop("survived", axis=1)
n_cols = predictors.shape[1]

In [17]:
# Import necessary modules
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

# Convert the target to categorical: target
target = to_categorical(df["survived"])

# Set up the model
model = Sequential()

# Add the first layer
model.add(Dense(32, activation='relu', input_shape=(n_cols,)))

# Add the output layer
model.add(Dense(2, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics='accuracy')


predictors = np.asarray(predictors).astype(np.float32)
target = np.asarray(target).astype(np.float32)

# Fit the model
model.fit(predictors, target)

28/28 [==============================] - 0s 677us/step - loss: 2.7902 - accuracy: 0.5915

# Making predictions

The trained network from your previous coding exercise is now stored as model. New data to make predictions is stored in a NumPy array as pred_data. Use model to make predictions on your new data.

In this exercise, your predictions will be probabilities, which is the most common way for data scientists to communicate their predictions to colleagues.

In [18]:
pred_data = predictors

In [19]:
# Specify, compile, and fit the model
model = Sequential()
model.add(Dense(32, activation='relu', input_shape = (n_cols,)))
model.add(Dense(2, activation='softmax'))
model.compile(optimizer='sgd', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model.fit(predictors, target)

# Calculate predictions: predictions
predictions = model.predict(pred_data)

# Calculate predicted probability of survival: predicted_prob_true
predicted_prob_true = predictions[:,1]

# Print predicted_prob_true
print(predicted_prob_true)

28/28 [==============================] - 0s 676us/step - loss: 2.9353 - accuracy: 0.5993
[1.74194068e-01 8.33082616e-01 9.27295089e-02 7.63990760e-01
 3.28397416e-02 6.34475350e-02 2.06412464e-01 4.65102255e-01
 1.66651368e-01 6.22896492e-01 4.52977359e-01 2.70240307e-02
 2.20257804e-01 2.44667694e-01 2.99241722e-01 7.55016366e-03
 4.73413229e-01 1.38851792e-01 1.86380148e-01 2.68239379e-02
 1.76724464e-01 9.44251865e-02 2.65651435e-01 5.71569622e-01
 5.30206978e-01 2.31811851e-01 3.00422590e-02 6.16938919e-02
 4.45696078e-02 6.24808744e-02 1.20317891e-01 4.83817041e-01
 4.27563190e-02 2.58847838e-04 7.15390801e-01 6.08862698e-01
 3.00968923e-02 1.99975938e-01 4.62428749e-01 3.71992052e-01
 2.00798977e-02 2.50459254e-01 4.00994681e-02 3.53566766e-01
 1.82238311e-01 6.52384833e-02 1.74707994e-01 4.27563190e-02
 2.64422387e-01 4.08199042e-01 4.98757541e-01 1.94640592e-01
 8.67970824e-01 3.00311893e-01 1.50585324e-01 5.08508265e-01
 2.26593018e-01 4.95553240e-02 4.23967987e-01 5.36852241e-01
 1.33757755e-01 8.08126926e-01 8.65971506e-01 4.50216651e-01
 3.03724289e-01 1.80684507e-01 9.76478457e-02 2.44227290e-01
 3.21681291e-01 1.43110096e-01 8.68012831e-02 6.00998402e-01
 5.86539268e-01 2.21471325e-01 7.40173042e-01 1.25194058e-01
 6.24808744e-02 6.52384833e-02 3.54680121e-01 1.03702560e-01
 2.00781137e-01 1.00403994e-01 4.33142111e-02 7.36218929e-01
 3.15770745e-01 1.38379961e-01 5.57154715e-01 6.52384833e-02
 7.35997111e-02 1.46387413e-01 8.26196000e-02 2.15784580e-01
 7.13955224e-01 3.28634501e-01 2.09418940e-04 6.52385205e-02
 1.73865929e-02 6.66461349e-01 1.71731830e-01 2.09776446e-01
 7.33986199e-02 6.24808744e-02 5.63927472e-01 5.29593788e-02
 2.58784480e-02 9.20574144e-02 1.55303717e-01 5.98228574e-02
 1.72434542e-02 2.31576487e-01 3.98217261e-01 4.27042097e-01
 1.80709705e-01 2.29984730e-01 3.08586031e-01 1.97309539e-01
 2.34083691e-05 2.52322197e-01 1.03264205e-01 3.95512581e-01
 6.20300591e-01 6.52384833e-02 3.12138379e-01 8.94945562e-02
 8.00397635e-01 4.44313914e-01 5.06942645e-02 1.31439060e-01
 2.29338616e-01 2.91893864e-03 2.80947220e-02 1.97679207e-01
 1.92506462e-02 3.00311893e-01 2.43402332e-01 2.56197006e-01
 5.65446019e-01 7.53164470e-01 3.41489285e-01 6.47356749e-01
 1.55621812e-01 1.41291246e-01 2.77611196e-01 1.96718469e-01
 3.34880769e-01 6.49824023e-01 1.01950802e-01 4.71992224e-01
 1.87024668e-01 3.52200791e-02 8.19419697e-03 6.37097478e-01
 5.96307218e-04 7.00756535e-02 4.92877811e-02 5.10619283e-01
 2.37131611e-01 7.19854012e-02 7.55067170e-02 7.90896356e-01
 4.79450598e-02 5.29035702e-02 1.13773592e-01 3.01800728e-01
 3.87673318e-01 4.90562469e-01 7.43227422e-01 1.43195182e-01
 2.67692059e-01 7.15315998e-01 4.06297483e-02 5.09754002e-01
 4.20882165e-01 1.97309539e-01 4.76352721e-02 3.11506629e-01
 3.51921737e-01 5.88595495e-02 1.47114649e-01 7.32856337e-04
 7.78156042e-01 1.51699841e-01 5.44420362e-01 3.75263482e-01
 3.96550030e-01 7.59611428e-01 1.41089365e-01 9.81101245e-02
 7.21568838e-02 2.53662597e-02 9.47556794e-02 3.25875908e-01
 2.06228867e-01 4.43184704e-01 8.36950690e-02 8.70872617e-01
 5.06942756e-02 9.26238485e-03 4.27563190e-02 2.19137326e-01
 1.12355180e-01 7.90896356e-01 2.02575196e-02 1.81991130e-03
 2.63495594e-01 4.19145554e-01 1.66657045e-01 2.36525923e-01
 2.37513095e-01 1.41921699e-01 1.29952788e-01 1.46641195e-01
 1.64889663e-01 1.47114649e-01 5.17535508e-02 6.32731140e-01
 8.27138722e-02 1.38125464e-01 7.56536603e-01 1.08935766e-01
 3.10432643e-01 2.01024801e-01 1.44671230e-03 6.24808632e-02
 8.10958862e-01 2.08413139e-01 3.17162246e-01 1.92418769e-01
 3.39773446e-01 3.25788468e-01 7.75577545e-01 7.85503685e-02
 2.74264091e-03 4.47674334e-01 2.06421003e-01 4.69004326e-02
 1.21155664e-01 4.66285139e-01 3.17162246e-01 9.66725126e-02
 1.14655346e-01 1.41089365e-01 1.21765003e-01 1.62448734e-01
 3.72755975e-02 8.79938066e-01 1.01846419e-01 2.68959075e-01
 7.30391860e-01 5.21010868e-02 4.79837134e-02 1.15195662e-01
 2.10585892e-02 2.07910478e-01 1.08161248e-01 1.80920824e-01
 7.17972755e-01 6.80877149e-01 3.77018191e-03 6.97052628e-02
 5.06942756e-02 4.36427593e-01 8.47927451e-01 4.64576500e-04
 4.27563190e-02 5.14743924e-02 6.40340388e-01 1.35038242e-01
 8.36970091e-01 5.84357679e-01 3.88190538e-01 7.09835719e-03
 9.01771113e-02 1.73357099e-01 4.27563190e-02 6.02384031e-01
 3.66746332e-03 2.22515711e-03 5.63947797e-01 1.79854184e-01
 6.92231479e-05 9.13651437e-02 3.49253684e-01 2.41812244e-01
 2.69292653e-01 3.82645354e-02 8.95957276e-02 1.77587360e-01
 3.52200791e-02 1.30816951e-01 6.43012226e-01 5.05984008e-01
 5.83343133e-02 1.30009115e-01 1.43754050e-01 3.03724289e-01
 1.09867372e-01 6.99472725e-02 3.75368595e-01 4.07992482e-01
 4.27563190e-02 2.83402890e-01 2.41568256e-02 9.66750830e-02
 6.52384833e-02 7.06526563e-02 6.06104553e-01 4.00184691e-01
 2.45710567e-01 7.69794166e-01 6.08940601e-01 5.27186878e-02
 3.84067893e-01 9.20574144e-02 1.39806524e-01 9.18832049e-02
 4.52767938e-01 7.37521006e-03 3.53613466e-01 6.82869554e-01
 1.64889663e-01 1.03218377e-01 1.02727428e-01 5.93827724e-01
 7.90896356e-01 6.18155599e-01 8.98902945e-05 5.95102496e-02
 2.23616228e-01 5.41637301e-01 2.56788015e-01 9.83385146e-02
 5.70284128e-01 5.50606132e-01 5.17856359e-01 6.24808744e-02
 7.63786495e-01 7.03363240e-01 4.70620301e-03 1.25122458e-01
 4.25319612e-01 7.87148327e-02 1.81571141e-01 2.43402332e-01
 7.49909952e-02 2.19137326e-01 3.68412472e-02 1.61234006e-01
 4.59663242e-01 1.11010969e-02 1.86094731e-01 4.94927227e-01
 3.33142281e-01 2.98302382e-01 3.00422590e-02 1.12355180e-01
 6.41601443e-01 4.68899831e-02 4.45696078e-02 4.45696078e-02
 2.10708126e-01 3.57538760e-01 1.88578870e-02 2.12747324e-02
 1.74707994e-01 5.91465198e-02 6.21985972e-01 2.68728975e-02
 4.27563190e-02 6.59950972e-01 7.51791894e-01 2.38130540e-01
 2.41812244e-01 3.92990470e-01 4.58547264e-01 7.22679913e-01
 1.32856131e-01 1.87683985e-01 6.13111220e-02 2.35279560e-01
 3.67695659e-01 3.84450167e-01 5.31425774e-02 7.52484202e-01
 6.24808744e-02 5.32827318e-01 3.54895979e-01 5.95102496e-02
 5.03339060e-02 2.95296133e-01 6.56027913e-01 1.94549963e-01
 9.47915092e-02 4.90536243e-01 2.82794297e-01 1.75585181e-01
 4.87260595e-02 9.46376175e-02 2.27795959e-01 1.41638279e-01
 1.43854525e-02 1.17647901e-01 2.10006803e-01 2.43810445e-01
 1.92335591e-01 1.96005762e-01 1.26576016e-03 4.71769720e-01
 1.94101527e-01 3.25788468e-01 6.24808744e-02 3.46145630e-02
 7.47489452e-01 2.22515711e-03 5.41709550e-03 5.40593378e-02
 3.06581080e-01 3.46092105e-01 1.47114649e-01 4.80296612e-01
 4.00994681e-02 1.79873034e-01 8.00084174e-02 1.99998856e-01
 4.90397841e-01 4.79837134e-02 3.28594297e-01 5.66531003e-01
 5.06942756e-02 5.44131063e-02 3.35317761e-01 1.61234006e-01
 1.20428868e-01 2.63255239e-01 4.54176426e-01 2.58072078e-01
 6.06814742e-01 3.66058975e-01 5.55076122e-01 9.73084569e-02
 1.09890752e-01 2.53149599e-01 1.35038242e-01 1.47599444e-01
 6.63881451e-02 2.41205379e-01 5.42668223e-01 1.86666951e-01
 4.97282088e-01 6.85465634e-02 2.20493048e-01 2.55006373e-01
 3.02640021e-01 8.92618775e-01 6.52384833e-02 5.76194488e-02
 1.45332497e-02 7.66278446e-01 4.58700070e-03 5.06942756e-02
 8.15356746e-02 3.97119373e-02 1.32413819e-01 1.46850068e-02
 6.52384833e-02 1.18892435e-02 2.22515711e-03 4.37661707e-02
 5.02613895e-02 4.23309058e-01 4.79837134e-02 2.41040532e-02
 2.29683191e-01 2.24243671e-01 1.79166213e-01 7.65083790e-01
 1.96005762e-01 7.06827193e-02 1.70170903e-01 4.17262226e-01
 5.00556052e-01 2.22515711e-03 1.76142273e-03 2.40242822e-04
 6.36909366e-01 3.25788468e-01 7.57017016e-01 3.95997576e-02
 7.19854012e-02 5.19439161e-01 2.55006373e-01 1.82872102e-01
 5.65864593e-02 2.55360212e-02 1.99975938e-01 1.32155746e-01
 8.34767282e-01 1.65294036e-01 3.19217741e-01 1.42067418e-01
 3.01800728e-01 1.45731896e-01 4.10054773e-02 2.87149623e-02
 4.35274661e-01 4.42680836e-01 2.00131953e-01 2.81213075e-01
 2.45258659e-01 6.94840968e-01 6.98347539e-02 6.52385205e-02
 1.64125174e-01 3.92190874e-01 1.37106583e-01 9.84907225e-02
 5.45355864e-02 2.28962794e-01 1.69176638e-01 5.28498366e-02
 6.56237841e-01 1.77587360e-01 3.00422590e-02 6.23365641e-01
 3.00968923e-02 8.55654664e-03 4.58700070e-03 2.14527309e-01
 1.43854525e-02 3.25756043e-01 4.01202351e-01 3.00968923e-02
 2.84186572e-01 2.17754573e-01 6.40606582e-02 4.48238373e-01
 9.81101245e-02 6.24689519e-01 1.54496938e-01 6.55614138e-01
 7.67829657e-01 5.19897521e-01 5.50825298e-01 2.40773454e-01
 8.93683076e-01 1.52685689e-02 6.14691556e-01 1.31833166e-01
 2.24583864e-01 4.91141438e-01 3.55821013e-01 3.33757639e-01
 5.20889871e-02 1.33660600e-01 1.41724527e-01 2.10585892e-02
 1.40244007e-01 2.10678592e-01 8.11506629e-01 1.04589447e-01
 5.06942756e-02 1.16905626e-02 1.92027554e-01 6.52384833e-02
 5.40593378e-02 4.55432385e-01 2.38204613e-01 2.65662640e-01
 3.00968923e-02 5.22104874e-02 5.69353520e-04 2.78884292e-01
 1.64376125e-01 4.27563190e-02 3.10432643e-01 3.36747915e-01
 7.52590224e-02 7.52984405e-01 1.14712656e-01 5.31425849e-02
 5.23377478e-01 7.44510174e-01 4.79970910e-02 4.31017816e-01
 5.57115972e-02 4.51526672e-01 2.51527913e-02 7.31240749e-01
 1.80709705e-01 6.52384833e-02 2.19825190e-02 8.60360861e-01
 2.22616526e-03 4.05813418e-02 1.79685578e-01 2.02668101e-01
 3.99564475e-01 5.52161328e-05 3.00422590e-02 5.10222435e-01
 5.24476230e-01 6.24808744e-02 6.86807990e-01 5.72590111e-03
 1.64478898e-01 1.03942737e-01 6.99546859e-02 4.69097525e-01
 6.62946999e-01 6.03723764e-01 2.20570758e-01 4.40275297e-02
 1.41089365e-01 5.06942756e-02 3.28397416e-02 6.18544340e-01
 1.32628173e-01 2.45633572e-01 4.03080881e-01 1.68218017e-01
 2.01722845e-01 6.23106003e-01 3.51856738e-01 1.95811167e-01
 3.14393222e-01 3.92257087e-02 2.55293469e-03 5.59467375e-01
 1.15461588e-01 5.04047312e-02 3.57869384e-03 9.28375113e-04
 3.10351461e-01 2.62642140e-03 5.13522744e-01 1.47599444e-01
 5.31425849e-02 2.66918778e-01 2.12013423e-01 1.98326588e-01
 2.15784580e-01 6.59950972e-01 3.91241193e-01 7.36926496e-01
 4.23309058e-01 8.71819317e-01 2.38204613e-01 5.18777482e-02
 5.45558743e-02 1.23638391e-01 6.24808744e-02 5.13173282e-01
 2.08320260e-01 4.39369120e-02 1.77219003e-01 6.70180738e-01
 6.24808744e-02 1.42443791e-01 2.73433596e-01 9.05252159e-01
 8.46306622e-01 5.36297308e-03 8.48639309e-02 2.13098843e-02
 2.29818538e-01 7.81359971e-01 2.43402332e-01 5.98228574e-02
 6.96499320e-03 7.66650200e-01 2.89572865e-01 7.68187940e-01
 1.17661089e-04 1.32015988e-01 2.22515711e-03 2.57036924e-01
 1.38698816e-01 2.56993592e-01 3.51894468e-01 4.08365950e-03
 4.79787886e-02 7.03679442e-01 2.46898711e-01 5.90457082e-01
 6.24834895e-02 6.87652051e-01 6.17357433e-01 2.92002946e-01
 2.57538497e-01 8.23351890e-02 7.81361938e-01 4.58218187e-01
 7.36926496e-01 8.79558921e-02 2.69227959e-02 8.98219459e-03
 5.72590111e-03 4.25100625e-02 8.69720101e-01 7.09581049e-03
 9.82368514e-02 1.73402980e-01 3.12635452e-01 1.17416784e-01
 1.22270048e-01 1.42432883e-01 2.01358125e-02 1.16628624e-01
 2.97825426e-01 1.80684507e-01 7.19566941e-01 2.81213075e-01
 4.14584041e-01 1.00196458e-01 7.91242812e-03 2.32230470e-01
 3.03006858e-01 1.22178212e-01 1.63503811e-01 4.26521190e-02
 4.27133679e-01 2.76151329e-01 9.44251865e-02 1.09354397e-02
 7.57638752e-01 2.34439597e-01 2.69513071e-01 4.25718799e-02
 4.42851782e-01 1.10133506e-01 2.14393795e-01 5.64888120e-01
 2.22515711e-03 2.73433596e-01 2.73433506e-01 2.21254215e-01
 1.25255316e-01 4.17202106e-03 6.24808744e-02 6.24808744e-02
 3.62718970e-01 8.14075530e-01 6.47398233e-02 3.06271672e-01
 6.11766726e-02 2.33500689e-01 5.56801081e-01 1.18654996e-01
 6.59442484e-01 5.04283048e-02 4.48064268e-01 4.82100964e-01
 6.21020384e-02 1.59947768e-01 7.02963114e-01 4.46755052e-01
 9.04013366e-02 3.34880769e-01 3.97119373e-02 7.26310611e-01
 1.54496938e-01 6.83976337e-03 1.72285244e-01 6.32733583e-01
 3.03061306e-01 8.47333133e-01 6.13848567e-01 4.59019095e-02
 2.56480157e-01 5.77157959e-02 1.73136607e-01 2.39275745e-03
 1.35669636e-03 3.00422590e-02 4.68333326e-02 2.56434977e-01
 5.06942756e-02 4.74296331e-01 5.04774079e-02 4.07406390e-01
 2.71528900e-01 5.87031126e-01 3.91592026e-01 2.97729969e-01
 1.16422236e-01 1.19285211e-01 2.05304250e-01 5.81244349e-01
 3.91188323e-01 8.66516113e-01 5.06942756e-02 6.11752927e-01
 7.78156042e-01 3.76045525e-01 1.28948182e-01 5.26527390e-02
 6.62102401e-02 5.70024103e-02 3.73428985e-02 2.44303957e-01
 9.44251865e-02 2.49463901e-01 2.36401394e-01 4.38263208e-01
 8.75655487e-02 5.94781898e-02 5.65758848e-04 2.11112261e-01
 5.26527390e-02 7.67536283e-01 1.15344889e-01 1.42738879e-01
 5.92720471e-02 4.65978861e-01 6.71548396e-02 2.62642140e-03
 1.29552752e-01 5.35090387e-01 3.42412572e-03 5.44461727e-01
 8.77520561e-01 1.13408111e-01 6.88963511e-04 1.67304888e-01
 4.09561306e-01 3.60233784e-02 7.36926496e-01 3.44107091e-01
 5.06942756e-02 6.19112194e-01 4.11065757e-01 4.32835668e-01
 3.00968923e-02 1.59179568e-01 2.69418925e-01 8.19076836e-01
 2.13431135e-01 6.52384833e-02 7.40173042e-01 3.51017505e-01
 2.17394486e-01 3.59946430e-01 3.60595345e-01 1.10983187e-02
 3.01800728e-01 6.78839488e-03 7.90896356e-01 1.91153456e-02
 4.79463130e-01 7.00067520e-01 4.54650849e-01 1.37568995e-05
 5.32996118e-01 5.97210348e-01 1.07103355e-01 2.78953195e-01
 6.41014576e-01 6.64662719e-02 2.82892585e-01 3.00968923e-02
 5.23762666e-02 3.20167124e-01 7.09045455e-02 7.78156161e-01
 2.60262758e-01 2.82812696e-02 1.66327849e-01 7.53786206e-01
 8.42444301e-02 4.76493001e-01 1.15461588e-01 4.34129179e-01
 1.68918539e-02 4.84603038e-03 2.78833568e-01 2.28434861e-01
 2.61156738e-01 2.38204613e-01 6.24808744e-02 8.41654837e-01
 3.68148386e-01 4.48861979e-02 1.91639811e-01 1.35874793e-01
 1.16422236e-01 1.82896271e-01 2.01024801e-01 6.44915521e-01
 2.70277321e-01 4.83700186e-01 4.27549705e-02]