In [20]:
import pandas as pd

# Example DataFrame
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8]
}
df = pd.DataFrame(data)

In [21]:
df.head()

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [22]:
x = df.sort_values("B")
x = x.set_index("A")

In [23]:
x["B"]

A
1    5
2    6
3    7
4    8
Name: B, dtype: int64

In [24]:
x["B"].max()

8

In [25]:
import numpy as np
np.median(x["B"])

6.5

In [26]:
y = x[x["B"] == x["B"].max()]
y

   B
A
4  8

In [35]:
y.index.values[0]

4